@host = localhost

### index
# GET /api/applications/proposes HTTP/1.1
# Host: {{ host }}
# Accept: application/json
# Authorization: Bearer {{ token }}


### show
# # @prompt application_id
# GET /api/applications/{{ application_id }}?perPage=20&page=1 HTTP/1.1
# Host: {{ host }}
# Accept: application/json
# Authorization: Bearer {{ token }}


### store
# @prompt file
POST /api/applications/{{ application_id }}/proposes HTTP/1.1
Host: {{ host }}
Accept: application/json
Content-Type: multipart/form-data; boundary=----storeForm
# boundatyは送信するデータの目印

------storeForm
Content-Disposition: form-data; name="title"

Test タイトル
------storeForm
Content-Disposition: form-data; name="body"

Test 本文
------storeForm
Content-Disposition: form-data; name="image"; filename="file.jpg"

< {{ file }}
------storeForm--



### accept
# @prompt application_id
# @prompt propose_id
POST /api/applications/{{ application_id }}/proposes/{{ propose_id }}/accept HTTP/1.1
Host: {{ host }}
Accept: application/json
Content-Type: application/json

{
    "_method": "PATCH",
    "message": "Test Message"
}


### destroy
# @prompt application_id
# @prompt propose_id
DELETE /api/applications/{{ application_id }}/proposes/{{ propose_id }} HTTP/1.1
Host: {{ host }}
Accept: application/json


### destroy
# @prompt application_id
DELETE /api/applications/{{ application_id }}/proposes/{{ propose_id }} HTTP/1.1
Host: {{ host }}
Accept: application/json
