@host = localhost

### index
GET /api/applications HTTP/1.1
Host: {{ host }}
Accept: application/json
# Authorization: Bearer {{ token }}


### show
# @prompt application_id
GET /api/applications/{{ application_id }}?perPage=20&page=1 HTTP/1.1
Host: {{ host }}
Accept: application/json
# Authorization: Bearer {{ token }}


### store
# @prompt file
POST /api/applications HTTP/1.1
Host: {{ host }}
Accept: application/json
Authorization: Bearer {{ token }}
Content-Type: multipart/form-data; boundary=----storeForm
# boundatyは送信するデータの目印

------storeForm
Content-Disposition: form-data; name="title"

Test タイトル
------storeForm
Content-Disposition: form-data; name="body"

Test 本文
------storeForm
Content-Disposition: form-data; name="image"; filename="file.jpg"

< {{ file }}
------storeForm--



### update
# @prompt file
POST /api/applications/1 HTTP/1.1
Host: {{ host }}
Accept: application/json
# Authorization: Bearer {{ token }}
Content-Type: multipart/form-data; boundary=----updateForm
# boundatyは送信するデータの目印

------updateForm
Content-Disposition: form-data; name="_method"

PATCH
------updateForm
Content-Disposition: form-data; name="title"

Test タイトル
------updateForm
Content-Disposition: form-data; name="body"

Test 本文
------updateForm
Content-Disposition: form-data; name="image"; filename="file.jpg"

< {{ file }}
------updateForm--



### destroy
# @prompt application_id
DELETE /api/applications/{{ application_id }} HTTP/1.1
Host: {{ host }}
Accept: application/json
# Authorization: Bearer {{ token }}
